---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: the-listener
spec:
  triggers:
  - binding:
      name: theTriggerBinding
    template:
      name: theTemplateTrigger
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: theTriggerBinding
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: theTemplateTrigger
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: pipelinerun-$(uid)
    spec:
      pipelineRef:
        name: pipeline
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
  - name: xx1
    taskRef:
      name: the-task
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: the-task
spec:
  steps:
  - args:
    - 01 version
    command:
    - echo
    image: ubuntu
    name: echo
  - args:
    - -l
    - /
    command:
    - ls
    image: ubuntu
    name: lslslash
  - args:
    - -l
    command:
    - ls
    image: ubuntu
    name: lsl-ubuntu
  - command:
    - pwd
    image: ubuntu
    name: pwd
  - command:
    - ls
    image: ubuntu
    name: ls
  - command:
    - env
    image: ubuntu
    name: env
  - name: build-and-push-1
    image: ubuntu
    command:
    - /bin/bash
    args:
    - -c
    - |
      set -ex
      find /workspace
  - args:
    - -c
    - cd /workspace; echo stuff > file; ls; echo "some more"; cat file
    command:
    - /bin/bash
    image: ubuntu
    name: write
  - args:
    - -l
    - /workspace
    command:
    - ls
    image: ubuntu
    name: ls-workspace
  - name: print-workspace
    image: ubuntu
    command:
    - /bin/bash
    args:
    - -c
    - |
      set -ex
      find -f /workspace/* | xargs cat -n

