apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: workspace
spec:
  triggers:
    - binding:
        name: simple-binding
      template:
        name: trigger-workspace
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: simple-binding

---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-workspace
spec:
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  1Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline-workspace
        workspaces:
          - name: pipeline-workspace
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc

---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-workspace
spec:
  workspaces:
  - name: pipeline-workspace
  params:
  - name: repository
    default: https://github.com/powellquiring/tekton.git
  - name: branch
    default: master
  tasks:
  - name: task1
    workspaces:
    - name: task-workspace
      workspace: pipeline-workspace          
    taskRef:
      name: task-workspace

---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-workspace
spec:
  workspaces:
  - name: task-workspace 
    # mountPath: /artifacts   
  steps:
  - name: echoenvvar
    image: ibmcom/pipeline-base-image
    command: ["/bin/bash", "-c"]
    args:
      - |
        set -x
        env 
        WS=$(workspaces.task-workspace.path)
        ls $WS
        CONFIG=/cd-config
        ls $CONFIG
        cd $CONFIG
        git clone 
        cat $CONFIG/toolchain.json
        jq <  $CONFIG/toolchain.json

    volumeMounts:
    - mountPath: /cd-config
      name: cd-config-volume
  volumes:
  - name: cd-config-volume
    configMap:
      name: toolchain
      items:
      - key: toolchain.json
        path: toolchain.json

