apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: clone-repo
spec:
  workspaces:
  - name: artifacts 
  inputs:
    params:
    - name: repository
      description: the git repo url
    - name: repository
      description: the git repository
    - name: branch
      description: the git branch
      default: master
  steps:
    - name: clone
      image: ibmcom/pipeline-base-image
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -x
          WS=$(workspaces.artifacts.path)
          REPOSITORY=$(inputs.params.repository)
          BRANCH=$(inputs.params.branch)
          ls $WS
          cd $WS
          git --version
          git clone --single-branch --branch $BRANCH $REPOSITORY
          echo hi >> hi
          ls $WS
          cat hi

---
