apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: simple-parameter
spec:
  triggers:
    - binding:
        name: theTriggerBinding
      template:
        name: theTemplateTrigger
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: theTriggerBinding
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: theTemplateTrigger
spec:
  #params:
  #  - name: var
  #    description: var example
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline
  #      params:
  #        - name: var
  #          value: $(params.var)
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  #params:
  #  - name: var
  #    description: var example in pipeline
  tasks:
    - name: xx1
  #    params:
  #      - name: var
  #        value: $(params.var)
      taskRef:
        name: the-var-task
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: the-var-task
spec:
  inputs:
    params:
      - name: var
        description: var example in task
        default: VALUE
  steps:
    - name: echoenvvar
      image: ubuntu
      env:
        - name: VAR
          value: $(inputs.params.var)
      command:
        - "/bin/bash"
      args:
        - "-c"
        - "echo 01 lab2 env VAR: $VAR"
    - name: echovar
      image: ubuntu
      command:
        - /bin/echo
      args:
        - $(inputs.params.var)
