apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: workspace
spec:
  triggers:
    - binding:
        name: simple-binding
      template:
        name: trigger-workspace
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: simple-binding

---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-workspace
spec:
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  1Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline-workspace
        workspaces:
          - name: pipeline-workspace
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc

---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-workspace
spec:
  workspaces:
  - name: pipeline-workspace
  tasks:
    - name: clone
      workspaces:
      - name: artifacts
        workspace: pipeline-workspace          
      taskRef:
        name: clone-repo-task-replacement
#      params:
#      - name: repository
#        value: https://github.com/powellquiring/tekton.git
#      - name: branch
#        value: master
    - name: task1
      workspaces:
      - name: task-workspace
        workspace: pipeline-workspace          
      taskRef:
        name: task-workspace
      runAfter:
      - clone
    - name: task2
      workspaces:
      - name: task-workspace
        workspace: pipeline-workspace          
      taskRef:
        name: task-workspace
      runAfter:
        - task1

---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: clone-repo-task-replacement
spec:
  workspaces:
  - name: artifacts 
  steps:
    - name: clone
      image: ibmcloudApi
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -x
          WS=$(workspaces.task-workspace.path)
          ls $WS
          cd $WS
          git clone --single-branch --branch master https://github.com/powellquiring/tekton
          git 
          echo hi >> hi
          ls $WS
          cat hi
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-workspace
spec:
  workspaces:
  - name: task-workspace 
    # mountPath: /artifacts   
  steps:
    - name: echoenvvar
      image: ubuntu
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -x
          echo 00 lab3
          WS=$(workspaces.task-workspace.path)
          ls $WS
          cd $WS
          echo hi >> hi
          ls $WS
          cat hi
