apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: user-defined-secret-variable
spec:
  triggers:
    - binding:
        name: simple-binding
      template:
        name: trigger-user-supplied-secret-variable
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: simple-binding
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-user-supplied-secret-variable
spec:
  params:
    - name: API_KEY
      description: the ibmcloud api key
  resourcetemplates:
    - apiVersion: v1
      kind: Secret
      # name must be cd-secret as defined by git task helper
      metadata:
        name: cd-secret
      type: Opaque
      # apikey value must be stored in the key API_KEY as defined by the git task helper
      stringData:
        API_KEY: $(params.API_KEY)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline-secret
        params:
          - name: task-pvc
            value: pipelinerun-$(uid)-pvc

---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-secret
spec:
  params:
    - name: task-pvc
  tasks:
#    - name: the-clone-repo-task
#      taskRef:
#        name: clone-repo-task
#      params:
#        - name: task-pvc
#          value: thepvc
#        - name: repository
#          value: https://github.com/powellquiring/tekton
#        - name: branch
#          value: master
    - name: pipelinesecret
      params:
        - name: task-pvc
          value: $(params.task-pvc)
      taskRef:
        name: secret-env-task
#      runAfter:
#        - the-clone-repo-task

---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: secret-env-task
spec:
  inputs:
    params:
      - name: task-pvc
  steps:
    - name: echoenvvar
      image: ubuntu
      env:
        - name: apikey
          valueFrom:
            secretKeyRef:
              name: cd-secret
              key: API_KEY
        - name: task_pvc
          value: $(inputs.params.task-pvc)
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo 03 lab3 secret in secrets slot_key VAR: $apikey
          echo task_pvc: $task_pvc
          ls /
          ls /gitrepo
          echo done
#          echo hi >> /gitrepo/hi
#          cat /gitrepo/hi
#      volumeMounts:
#        - mountPath: /gitrepo
#          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: pipelinerun-22c0d52b-5b1e-4d08-ab9f-9dc2526057b2-pvc

#        claimName: $(inputs.params.task-pvc)
#      emptyDir: {}

